[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
roullete = "GR7AVT5cwad3decrFzMKNz2tKnT5f3BALirQDegq63iZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/advait/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
